# Generated by Django 5.1.4 on 2025-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_date', models.DateField(auto_now_add=True)),
                ('winning_numbers', models.JSONField()),
            ],
        ),
    ]
