# Generated by Django 5.1.4 on 2025-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0002_lottowinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottowinner',
            name='extra_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
