# Generated by Django 5.1.4 on 2025-01-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0003_lottowinner_extra_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottowinner',
            name='winning_date',
            field=models.DateField(auto_now=True),
        ),
    ]
