# Generated by Django 5.1.4 on 2025-01-10 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0004_alter_lottowinner_winning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottowinner',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
