# Generated by Django 5.1.4 on 2025-01-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0005_lottowinner_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottowinner',
            name='limit_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
