# Generated by Django 5.1.4 on 2025-01-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0006_lottowinner_limit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottowinner',
            name='limit_count',
        ),
    ]
