# Generated by Django 5.1.4 on 2025-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0007_remove_lottowinner_limit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_number', models.IntegerField()),
            ],
        ),
    ]
