# Generated by Django 5.1.4 on 2025-01-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0008_lottoadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottowinner',
            name='created_date',
        ),
    ]
