# Generated by Django 5.1.4 on 2025-01-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0009_remove_lottowinner_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottowinner',
            name='winning_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
